[package]
name = "fuseless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.1.23"
sysinfo = "0.26.2"

[lib]
crate-type = ["cdylib"]
